# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.5.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

import typing
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _py_BayesianBlocks
else:
    import _py_BayesianBlocks

import builtins as __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _py_BayesianBlocks.delete_SwigPyIterator

    def value(self):
        return _py_BayesianBlocks.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _py_BayesianBlocks.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _py_BayesianBlocks.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _py_BayesianBlocks.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _py_BayesianBlocks.SwigPyIterator_equal(self, x)

    def copy(self):
        return _py_BayesianBlocks.SwigPyIterator_copy(self)

    def __next__(self):
        return _py_BayesianBlocks.SwigPyIterator___next__(self)

    def previous(self):
        return _py_BayesianBlocks.SwigPyIterator_previous(self)

    def advance(self, n):
        return _py_BayesianBlocks.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _py_BayesianBlocks.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _py_BayesianBlocks.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _py_BayesianBlocks.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _py_BayesianBlocks.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _py_BayesianBlocks.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _py_BayesianBlocks.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _py_BayesianBlocks:
_py_BayesianBlocks.SwigPyIterator_swigregister(SwigPyIterator)
class DoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _py_BayesianBlocks.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __bool__(self):
        return _py_BayesianBlocks.DoubleVector___bool__(self)

    def __len__(self):
        return _py_BayesianBlocks.DoubleVector___len__(self)

    def __delitem__(self, *args):
        return _py_BayesianBlocks.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _py_BayesianBlocks.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _py_BayesianBlocks.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _py_BayesianBlocks.DoubleVector_pop(self)

    def append(self, x):
        return _py_BayesianBlocks.DoubleVector_append(self, x)

    def empty(self):
        return _py_BayesianBlocks.DoubleVector_empty(self)

    def size(self):
        return _py_BayesianBlocks.DoubleVector_size(self)

    def swap(self, v):
        return _py_BayesianBlocks.DoubleVector_swap(self, v)

    def begin(self):
        return _py_BayesianBlocks.DoubleVector_begin(self)

    def end(self):
        return _py_BayesianBlocks.DoubleVector_end(self)

    def rbegin(self):
        return _py_BayesianBlocks.DoubleVector_rbegin(self)

    def rend(self):
        return _py_BayesianBlocks.DoubleVector_rend(self)

    def clear(self):
        return _py_BayesianBlocks.DoubleVector_clear(self)

    def get_allocator(self):
        return _py_BayesianBlocks.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _py_BayesianBlocks.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _py_BayesianBlocks.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        _py_BayesianBlocks.DoubleVector_swiginit(self, _py_BayesianBlocks.new_DoubleVector(*args))

    def push_back(self, x):
        return _py_BayesianBlocks.DoubleVector_push_back(self, x)

    def front(self):
        return _py_BayesianBlocks.DoubleVector_front(self)

    def back(self):
        return _py_BayesianBlocks.DoubleVector_back(self)

    def assign(self, n, x):
        return _py_BayesianBlocks.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _py_BayesianBlocks.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _py_BayesianBlocks.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _py_BayesianBlocks.DoubleVector_reserve(self, n)

    def capacity(self):
        return _py_BayesianBlocks.DoubleVector_capacity(self)
    __swig_destroy__ = _py_BayesianBlocks.delete_DoubleVector

# Register DoubleVector in _py_BayesianBlocks:
_py_BayesianBlocks.DoubleVector_swigregister(DoubleVector)
class PairDoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _py_BayesianBlocks.PairDoubleVector_swiginit(self, _py_BayesianBlocks.new_PairDoubleVector(*args))
    first = property(_py_BayesianBlocks.PairDoubleVector_first_get, _py_BayesianBlocks.PairDoubleVector_first_set)
    second = property(_py_BayesianBlocks.PairDoubleVector_second_get, _py_BayesianBlocks.PairDoubleVector_second_set)
    def __len__(self):
        return 2
    def __repr__(self):
        return str((self.first, self.second))
    def __getitem__(self, index): 
        if not (index % 2):
            return self.first
        else:
            return self.second
    def __setitem__(self, index, val):
        if not (index % 2):
            self.first = val
        else:
            self.second = val
    __swig_destroy__ = _py_BayesianBlocks.delete_PairDoubleVector

# Register PairDoubleVector in _py_BayesianBlocks:
_py_BayesianBlocks.PairDoubleVector_swigregister(PairDoubleVector)
class DoubleVectorVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _py_BayesianBlocks.DoubleVectorVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __bool__(self):
        return _py_BayesianBlocks.DoubleVectorVector___bool__(self)

    def __len__(self):
        return _py_BayesianBlocks.DoubleVectorVector___len__(self)

    def __delitem__(self, *args):
        return _py_BayesianBlocks.DoubleVectorVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _py_BayesianBlocks.DoubleVectorVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _py_BayesianBlocks.DoubleVectorVector___setitem__(self, *args)

    def pop(self):
        return _py_BayesianBlocks.DoubleVectorVector_pop(self)

    def append(self, x):
        return _py_BayesianBlocks.DoubleVectorVector_append(self, x)

    def empty(self):
        return _py_BayesianBlocks.DoubleVectorVector_empty(self)

    def size(self):
        return _py_BayesianBlocks.DoubleVectorVector_size(self)

    def swap(self, v):
        return _py_BayesianBlocks.DoubleVectorVector_swap(self, v)

    def begin(self):
        return _py_BayesianBlocks.DoubleVectorVector_begin(self)

    def end(self):
        return _py_BayesianBlocks.DoubleVectorVector_end(self)

    def rbegin(self):
        return _py_BayesianBlocks.DoubleVectorVector_rbegin(self)

    def rend(self):
        return _py_BayesianBlocks.DoubleVectorVector_rend(self)

    def clear(self):
        return _py_BayesianBlocks.DoubleVectorVector_clear(self)

    def get_allocator(self):
        return _py_BayesianBlocks.DoubleVectorVector_get_allocator(self)

    def pop_back(self):
        return _py_BayesianBlocks.DoubleVectorVector_pop_back(self)

    def erase(self, *args):
        return _py_BayesianBlocks.DoubleVectorVector_erase(self, *args)

    def __init__(self, *args):
        _py_BayesianBlocks.DoubleVectorVector_swiginit(self, _py_BayesianBlocks.new_DoubleVectorVector(*args))

    def push_back(self, x):
        return _py_BayesianBlocks.DoubleVectorVector_push_back(self, x)

    def front(self):
        return _py_BayesianBlocks.DoubleVectorVector_front(self)

    def back(self):
        return _py_BayesianBlocks.DoubleVectorVector_back(self)

    def assign(self, n, x):
        return _py_BayesianBlocks.DoubleVectorVector_assign(self, n, x)

    def resize(self, *args):
        return _py_BayesianBlocks.DoubleVectorVector_resize(self, *args)

    def insert(self, *args):
        return _py_BayesianBlocks.DoubleVectorVector_insert(self, *args)

    def reserve(self, n):
        return _py_BayesianBlocks.DoubleVectorVector_reserve(self, n)

    def capacity(self):
        return _py_BayesianBlocks.DoubleVectorVector_capacity(self)
    __swig_destroy__ = _py_BayesianBlocks.delete_DoubleVectorVector

# Register DoubleVectorVector in _py_BayesianBlocks:
_py_BayesianBlocks.DoubleVectorVector_swigregister(DoubleVectorVector)
class IntVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _py_BayesianBlocks.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __bool__(self):
        return _py_BayesianBlocks.IntVector___bool__(self)

    def __len__(self):
        return _py_BayesianBlocks.IntVector___len__(self)

    def __delitem__(self, *args):
        return _py_BayesianBlocks.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _py_BayesianBlocks.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _py_BayesianBlocks.IntVector___setitem__(self, *args)

    def pop(self):
        return _py_BayesianBlocks.IntVector_pop(self)

    def append(self, x):
        return _py_BayesianBlocks.IntVector_append(self, x)

    def empty(self):
        return _py_BayesianBlocks.IntVector_empty(self)

    def size(self):
        return _py_BayesianBlocks.IntVector_size(self)

    def swap(self, v):
        return _py_BayesianBlocks.IntVector_swap(self, v)

    def begin(self):
        return _py_BayesianBlocks.IntVector_begin(self)

    def end(self):
        return _py_BayesianBlocks.IntVector_end(self)

    def rbegin(self):
        return _py_BayesianBlocks.IntVector_rbegin(self)

    def rend(self):
        return _py_BayesianBlocks.IntVector_rend(self)

    def clear(self):
        return _py_BayesianBlocks.IntVector_clear(self)

    def get_allocator(self):
        return _py_BayesianBlocks.IntVector_get_allocator(self)

    def pop_back(self):
        return _py_BayesianBlocks.IntVector_pop_back(self)

    def erase(self, *args):
        return _py_BayesianBlocks.IntVector_erase(self, *args)

    def __init__(self, *args):
        _py_BayesianBlocks.IntVector_swiginit(self, _py_BayesianBlocks.new_IntVector(*args))

    def push_back(self, x):
        return _py_BayesianBlocks.IntVector_push_back(self, x)

    def front(self):
        return _py_BayesianBlocks.IntVector_front(self)

    def back(self):
        return _py_BayesianBlocks.IntVector_back(self)

    def assign(self, n, x):
        return _py_BayesianBlocks.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _py_BayesianBlocks.IntVector_resize(self, *args)

    def insert(self, *args):
        return _py_BayesianBlocks.IntVector_insert(self, *args)

    def reserve(self, n):
        return _py_BayesianBlocks.IntVector_reserve(self, n)

    def capacity(self):
        return _py_BayesianBlocks.IntVector_capacity(self)
    __swig_destroy__ = _py_BayesianBlocks.delete_IntVector

# Register IntVector in _py_BayesianBlocks:
_py_BayesianBlocks.IntVector_swigregister(IntVector)
class BayesianBlocks(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _py_BayesianBlocks.BayesianBlocks_swiginit(self, _py_BayesianBlocks.new_BayesianBlocks(*args))

    def globalOpt(self, ncp_prior, xx, yy):
        return _py_BayesianBlocks.BayesianBlocks_globalOpt(self, ncp_prior, xx, yy)

    def blockCost(self, imin, imax):
        return _py_BayesianBlocks.BayesianBlocks_blockCost(self, imin, imax)

    def blockSize(self, imin, imax):
        return _py_BayesianBlocks.BayesianBlocks_blockSize(self, imin, imax)

    def blockContent(self, imin, imax):
        return _py_BayesianBlocks.BayesianBlocks_blockContent(self, imin, imax)

    def cellContent(self):
        return _py_BayesianBlocks.BayesianBlocks_cellContent(self)

    def cellErrors(self):
        return _py_BayesianBlocks.BayesianBlocks_cellErrors(self)

    def setCellSizes(self, cellSizes):
        return _py_BayesianBlocks.BayesianBlocks_setCellSizes(self, cellSizes)

    @staticmethod
    def ncp_prior(nevents, fp_frac):
        return _py_BayesianBlocks.BayesianBlocks_ncp_prior(nevents, fp_frac)

    @staticmethod
    def enableFPE():
        return _py_BayesianBlocks.BayesianBlocks_enableFPE()

    def lightCurve(self, ncp_prior):
        return _py_BayesianBlocks.BayesianBlocks_lightCurve(self, ncp_prior)
    __swig_destroy__ = _py_BayesianBlocks.delete_BayesianBlocks

# Register BayesianBlocks in _py_BayesianBlocks:
_py_BayesianBlocks.BayesianBlocks_swigregister(BayesianBlocks)

