# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...4.2)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS ST::ape ST::pcheck ST::pget ST::plist ST::pquery ST::pquery2 ST::pset ST::punlearn)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target ST::ape
add_library(ST::ape SHARED IMPORTED)

set_target_properties(ST::ape PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/jamrhein/FALL_2026_Builds/0819/ScienceTools/src/ape/include"
)

# Create imported target ST::pcheck
add_executable(ST::pcheck IMPORTED)

# Create imported target ST::pget
add_executable(ST::pget IMPORTED)

# Create imported target ST::plist
add_executable(ST::plist IMPORTED)

# Create imported target ST::pquery
add_executable(ST::pquery IMPORTED)

# Create imported target ST::pquery2
add_executable(ST::pquery2 IMPORTED)

# Create imported target ST::pset
add_executable(ST::pset IMPORTED)

# Create imported target ST::punlearn
add_executable(ST::punlearn IMPORTED)

# Import target "ST::ape" for configuration "RelWithDebInfo"
set_property(TARGET ST::ape APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(ST::ape PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/jamrhein/FALL_2026_Builds/0819/ScienceTools/RelWithDebInfo/ape/libape_3.dylib"
  IMPORTED_SONAME_RELWITHDEBINFO "@rpath/libape_3.dylib"
  )

# Import target "ST::pcheck" for configuration "RelWithDebInfo"
set_property(TARGET ST::pcheck APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(ST::pcheck PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/jamrhein/FALL_2026_Builds/0819/ScienceTools/RelWithDebInfo/ape/pcheck"
  )

# Import target "ST::pget" for configuration "RelWithDebInfo"
set_property(TARGET ST::pget APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(ST::pget PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/jamrhein/FALL_2026_Builds/0819/ScienceTools/RelWithDebInfo/ape/pget"
  )

# Import target "ST::plist" for configuration "RelWithDebInfo"
set_property(TARGET ST::plist APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(ST::plist PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/jamrhein/FALL_2026_Builds/0819/ScienceTools/RelWithDebInfo/ape/plist"
  )

# Import target "ST::pquery" for configuration "RelWithDebInfo"
set_property(TARGET ST::pquery APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(ST::pquery PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/jamrhein/FALL_2026_Builds/0819/ScienceTools/RelWithDebInfo/ape/pquery"
  )

# Import target "ST::pquery2" for configuration "RelWithDebInfo"
set_property(TARGET ST::pquery2 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(ST::pquery2 PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/jamrhein/FALL_2026_Builds/0819/ScienceTools/RelWithDebInfo/ape/pquery2"
  )

# Import target "ST::pset" for configuration "RelWithDebInfo"
set_property(TARGET ST::pset APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(ST::pset PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/jamrhein/FALL_2026_Builds/0819/ScienceTools/RelWithDebInfo/ape/pset"
  )

# Import target "ST::punlearn" for configuration "RelWithDebInfo"
set_property(TARGET ST::punlearn APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(ST::punlearn PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/jamrhein/FALL_2026_Builds/0819/ScienceTools/RelWithDebInfo/ape/punlearn"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
