cflags:
  - "-D_FPU_SINGLE=0x0000 -D_FPU_DOUBLE=0x0300 -D_FPU_EXTENDED=0x0300 -D_FPU_RC_NEAREST=0x0000 -D_FPU_RC_DOWN=0x0400 -D_FPU_RC_UP=0x0800 -D_FPU_RC_ZERO=0x0C00 -D_FPU_MASK_IM=0x0001 -D_FPU_MASK_DM=0x0002 -D_FPU_MASK_ZM=0x0004 -D_FPU_MASK_OM=0x0008 -D_FPU_MASK_UM=0x0010 -D_FPU_MASK_PM=0x0020"
