package:
  name: fermitools
  version: 2.4.0
source:
  git_url: https://github.com/fermi-lat/Sciencetools.git
  git_rev: master
build:
  number: '0'
  script_env:
    - MACOS_ARCH
  run_exports:
    - cfitsio >=4.6.2,<4.6.3.0a0
    - clhep
    - cppunit
    - f2c
    - fftw
    - gsl
    - healpix_cxx
    - numpy >=1.18,<2.0
    - python >=3.11.13,<3.12.0a0
    - readline >=8.2,<8.3.0a0
    - wcslib
    - xerces-c
  entry_points:
    - gtburst            = fermitools.gtburst:main
    - fits2png           = fermitools.GtBurst.commands.fits2png:__main__
    - fromLogToScript    = fermitools.GtBurst.commands.fromLogToScript:__main__
    - gtbuildxmlmodel    = fermitools.GtBurst.commands.gtbuildxmlmodel:__main__
    - gtburstInstTest    = fermitools.GtBurst.commands.gtburstInstTest:__main__
    - gtconvertxmlmodel  = fermitools.GtBurst.commands.gtconvertxmlmodel:__main__
    - gtdocountsmap      = fermitools.GtBurst.commands.gtdocountsmap:__main__
    - gtdolike           = fermitools.GtBurst.commands.gtdolike:__main__
    - gtdosed            = fermitools.GtBurst.commands.gtdosed:__main__
    - gtdosimulation     = fermitools.GtBurst.commands.gtdosimulation:__main__
    - gtdotsmap          = fermitools.GtBurst.commands.gtdotsmap:__main__
    - gtdownloadGBMdata  = fermitools.GtBurst.commands.gtdownloadGBMdata:__main__
    - gtdownloadLATdata  = fermitools.GtBurst.commands.gtdownloadLATdata:__main__
    - gtdownloadLLEdata  = fermitools.GtBurst.commands.gtdownloadLLEdata:__main__
    - gteditxmlmodel.py  = fermitools.GtBurst.commands.gteditxmlmodel:__main__
    - gteditxmlmodelsim  = fermitools.GtBurst.commands.gteditxmlmodelsim:__main__
    - gtinteractiveRaDec = fermitools.GtBurst.commands.gtinteractiveRaDec:__main__
    - gtllebin           = fermitools.GtBurst.commands.gtllebin:__main__
    - gtllebindef        = fermitools.GtBurst.commands.gtllebindef:__main__
    - gtllebkg           = fermitools.GtBurst.commands.gtllebkg:__main__
    - gtllebkgbindef     = fermitools.GtBurst.commands.gtllebkgbindef:__main__
    - gtllebkgGUI        = fermitools.GtBurst.commands.gtllebkgGUI:__main__
    - gtllesrc           = fermitools.GtBurst.commands.gtllesrc:__main__
    - gtllesrcbindef     = fermitools.GtBurst.commands.gtllesrcbindef:__main__
    - modeleditor        = fermitools.ModelEditor:main
    - ObsSim             = fermitools.ObsSim:main
requirements:
  build:
    - libcurl 8.14.1 h73640d1_0
    - libnghttp2 1.67.0 hc438710_0
    - icu 75.1 hfee45f7_0
    - openssl 3.5.3 h5503f6c_0
    - libsqlite 3.50.4 h4237e3c_0
    - bzip2 1.0.8 hd037594_8
    - tk 8.6.13 h892fb3f_2
    - pip 25.2 pyh8b19718_0
    - libglib 2.86.0 h1bb475b_0
    - pcre 8.45 hbdafb3b_0
    - libzlib 1.3.1 h8359307_2
    - setuptools 80.9.0 pyhff2d567_0
    - libexpat 2.7.1 hec049ff_0
    - make 4.4.1 hc9fafa5_2
    - libintl 0.25.1 h493aca8_0
    - wheel 0.45.1 pyhd8ed1ab_1
    - libev 4.33 h93a5062_2
    - pcre2 10.46 h7125dd6_0
    - python 3.11.13 hc22306f_0_cpython
    - zstd 1.5.7 h6491c7d_2
    - libssh2 1.11.1 h1590b86_0
    - pkg-config 0.29.2 hde07d2e_1009
    - swig 4.0.2 hc25a523_2
    - libiconv 1.18 h23cfdf5_2
    - ncurses 6.5 h5e97a16_3
    - cfitsio 4.6.2 h7200ff5_1
    - c-ares 1.34.5 h5505292_0
    - krb5 1.21.3 h237132a_0
    - readline 8.2 h1d1bf99_2
    - ca-certificates 2025.8.3 hbd8a1cb_0
    - tzdata 2025b h78e105d_0
    - libedit 3.1.20250104 pl5321hafb1f1b_0
    - libcxx 21.1.1 hf598326_0
    - rhash 1.4.6 h5505292_1
    - libuv 1.51.0 h6caf38d_1
    - cmake 4.1.1 hae74ae4_0
    - libffi 3.4.6 h1da3d7d_1
    - liblzma 5.8.1 h39f12f2_2
  host:
    - bzip2 1.0.8 hd037594_8
    - c-ares 1.34.5 h5505292_0
    - ca-certificates 2025.8.3 hbd8a1cb_0
    - icu 75.1 hfee45f7_0
    - libcxx 21.1.1 hf598326_0
    - libev 4.33 h93a5062_2
    - libexpat 2.7.1 hec049ff_0
    - libffi 3.4.6 h1da3d7d_1
    - liblzma 5.8.1 h39f12f2_2
    - libzlib 1.3.1 h8359307_2
    - ncurses 6.5 h5e97a16_3
    - tzdata 2025b h78e105d_0
    - libedit 3.1.20250104 pl5321hafb1f1b_0
    - libsqlite 3.50.4 h4237e3c_0
    - openssl 3.5.3 h5503f6c_0
    - readline 8.2 h1d1bf99_2
    - tk 8.6.13 h892fb3f_2
    - zlib 1.3.1 h8359307_2
    - zstd 1.5.7 h6491c7d_2
    - krb5 1.21.3 h237132a_0
    - libnghttp2 1.67.0 hc438710_0
    - libssh2 1.11.1 h1590b86_0
    - python 3.11.13 hc22306f_0_cpython
    - libcurl 8.14.1 h73640d1_0
    - setuptools 80.9.0 pyhff2d567_0
    - wheel 0.45.1 pyhd8ed1ab_1
    - cfitsio 4.6.2 h7200ff5_1
    - pip 25.2 pyh8b19718_0
  run:
    - python_abi 3.11.* *_cp311
    - python >=3.11,<3.12.0a0
    - cfitsio >=4.6.2,<4.6.3.0a0
    - fermitools-data
    - libzlib >=1.3.1,<2.0a0
  test: []
  imports:
    - py_facilities
    - pyLikelihood
    - UnbinnedAnalysis
  requires:
    - fermitools-test-scripts-data
    - junit-xml
  files:
    - tests/ST-unit-test
  commands:
    - tests/ST-unit-test -w
about:
  home: https://github.com/fermi-lat/Sciencetools
  license: BSD-3-Clause
  summary: Conda recipe files for the Fermi Sciencetools analysis package Fermitools
  license_file: LICENSE.txt
extra:
  final: true
  copy_test_source_files: true
