# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.5.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

import typing
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _py_facilities
else:
    import _py_facilities

import builtins as __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _py_facilities.delete_SwigPyIterator

    def value(self):
        return _py_facilities.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _py_facilities.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _py_facilities.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _py_facilities.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _py_facilities.SwigPyIterator_equal(self, x)

    def copy(self):
        return _py_facilities.SwigPyIterator_copy(self)

    def __next__(self):
        return _py_facilities.SwigPyIterator___next__(self)

    def previous(self):
        return _py_facilities.SwigPyIterator_previous(self)

    def advance(self, n):
        return _py_facilities.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _py_facilities.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _py_facilities.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _py_facilities.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _py_facilities.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _py_facilities.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _py_facilities.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _py_facilities:
_py_facilities.SwigPyIterator_swigregister(SwigPyIterator)
class commonUtilities(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def getDataPath(package):
        return _py_facilities.commonUtilities_getDataPath(package)

    @staticmethod
    def getJobOptionsPath(package):
        return _py_facilities.commonUtilities_getJobOptionsPath(package)

    @staticmethod
    def getXmlPath(package):
        return _py_facilities.commonUtilities_getXmlPath(package)

    @staticmethod
    def getPfilesPath(package):
        return _py_facilities.commonUtilities_getPfilesPath(package)

    @staticmethod
    def getPackagePath(package):
        return _py_facilities.commonUtilities_getPackagePath(package)

    @staticmethod
    def setEnvironment(name, value, overwrite=False):
        return _py_facilities.commonUtilities_setEnvironment(name, value, overwrite)

    @staticmethod
    def getEnvironment(name):
        return _py_facilities.commonUtilities_getEnvironment(name)

    @staticmethod
    def joinPath(first, second):
        return _py_facilities.commonUtilities_joinPath(first, second)

    @staticmethod
    def setupEnvironment():
        return _py_facilities.commonUtilities_setupEnvironment()

    def __init__(self):
        _py_facilities.commonUtilities_swiginit(self, _py_facilities.new_commonUtilities())
    __swig_destroy__ = _py_facilities.delete_commonUtilities

# Register commonUtilities in _py_facilities:
_py_facilities.commonUtilities_swigregister(commonUtilities)

