#pragma once
/* Auto Generated by CMAKE. Do not change */

#define PROJECT_NAME "fermitools"
#define PROJECT_VERSION "2.4.0"
#define PROJECT_VERSION_MAJOR "2"
#define PROJECT_VERSION_MINOR "4"
#define PROJECT_VERSION_PATCH "0"

#define PACKAGES "ape astro BayesianBlocks burstFit catalogAccess celestialSources dataSubselector embed_python evtbin facilities fermitools-fhelp fitsGen flux healpix hoops irfs Likelihood map_tools Minuit2 modelEditor observationSim optimizers orbitSim pyBurstAnalysisGUI pyExposure pyLikelihood rspgen sane sourceIdentify SolarSystemTools st_facilities st_stream st_graph st_app tip timeSystem xmlBase"
