# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_GID "-1")
set(CPACK_ARCHIVE_UID "-1")
set(CPACK_BINARY_BUNDLE "OFF")
set(CPACK_BINARY_DEB "OFF")
set(CPACK_BINARY_DRAGNDROP "OFF")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_PRODUCTBUILD "OFF")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BUILD_SOURCE_DIRS "/Users/jamrhein/FALL_2026_Builds/0819/ScienceTools;/Users/jamrhein/FALL_2026_Builds/0819/ScienceTools/RelWithDebInfo")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "Devel;Development;Unspecified")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/Users/jamrhein/miniforge3/envs/fermi-0819master/share/cmake-4.4/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "fermitools built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "TGZ;ZIP")
set(CPACK_IGNORE_FILES "/test/CMakeLists.txt;/test/Makefile;/test/testMinimizer.cxx;/test/testNdimFit.cxx;/test/testUnbinGausFit.cxx;/test/testUserFunc.cxx;/Module.mk;/.git;/dist;/.*build.*;/\\.DS_Store;/.*\\.egg-info;/var;/Pipfile.*$")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALLED_DIRECTORIES "/Users/jamrhein/FALL_2026_Builds/0819/ScienceTools;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/Users/jamrhein/miniforge3/envs/fermi-0819master")
set(CPACK_MODULE_PATH "/Users/jamrhein/FALL_2026_Builds/0819/ScienceTools/cmake")
set(CPACK_NSIS_DISPLAY_NAME "fermitools 6.22.6")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "fermitools 6.22.6")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/opt/homebrew/opt/llvm/bin/llvm-objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/opt/homebrew/opt/llvm/bin/llvm-objdump")
set(CPACK_OSX_SYSROOT "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk")
set(CPACK_OUTPUT_CONFIG_FILE "/Users/jamrhein/FALL_2026_Builds/0819/ScienceTools/RelWithDebInfo/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/Users/jamrhein/miniforge3/envs/fermi-0819master/share/cmake-4.4/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Minuit2 standalone fitting tool")
set(CPACK_PACKAGE_FILE_NAME "fermitools-6.22.6-Source")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "fermitools 6.22.6")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "fermitools 6.22.6")
set(CPACK_PACKAGE_NAME "fermitools")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "root.cern.ch")
set(CPACK_PACKAGE_VERSION "6.22.6")
set(CPACK_PACKAGE_VERSION_MAJOR "6")
set(CPACK_PACKAGE_VERSION_MINOR "22")
set(CPACK_PACKAGE_VERSION_PATCH "6")
set(CPACK_READELF_EXECUTABLE "/opt/homebrew/opt/llvm/bin/llvm-readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/Users/jamrhein/FALL_2026_Builds/0819/ScienceTools/src/Minuit2/LICENSE")
set(CPACK_RESOURCE_FILE_README "/Users/jamrhein/FALL_2026_Builds/0819/ScienceTools/src/Minuit2/README.md")
set(CPACK_RESOURCE_FILE_WELCOME "/Users/jamrhein/miniforge3/envs/fermi-0819master/share/cmake-4.4/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TGZ;ZIP")
set(CPACK_SOURCE_IGNORE_FILES "/test/CMakeLists.txt;/test/Makefile;/test/testMinimizer.cxx;/test/testNdimFit.cxx;/test/testUnbinGausFit.cxx;/test/testUserFunc.cxx;/Module.mk;/.git;/dist;/.*build.*;/\\.DS_Store;/.*\\.egg-info;/var;/Pipfile.*$")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/Users/jamrhein/FALL_2026_Builds/0819/ScienceTools;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/Users/jamrhein/FALL_2026_Builds/0819/ScienceTools/RelWithDebInfo/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "fermitools-6.22.6-Source")
set(CPACK_SOURCE_TOPLEVEL_TAG "Darwin-Source")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Darwin")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Darwin-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/Users/jamrhein/FALL_2026_Builds/0819/ScienceTools/RelWithDebInfo/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
