# CMake generated Testfile for 
# Source directory: /Users/jamrhein/FALL_2026_Builds/0819/ScienceTools
# Build directory: /Users/jamrhein/FALL_2026_Builds/0819/ScienceTools/RelWithDebInfo
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("externals/cfitsio")
subdirs("externals/clhep")
subdirs("externals/cppunit")
subdirs("externals/f2c")
subdirs("externals/fftw")
subdirs("externals/gsl")
subdirs("externals/healpix_cxx")
subdirs("externals/wcslib")
subdirs("ape")
subdirs("astro")
subdirs("BayesianBlocks")
subdirs("burstFit")
subdirs("catalogAccess")
subdirs("celestialSources")
subdirs("dataSubselector")
subdirs("embed_python")
subdirs("evtbin")
subdirs("facilities")
subdirs("fermitools-fhelp")
subdirs("fitsGen")
subdirs("flux")
subdirs("healpix")
subdirs("hoops")
subdirs("irfs")
subdirs("Likelihood")
subdirs("map_tools")
subdirs("Minuit2")
subdirs("modelEditor")
subdirs("observationSim")
subdirs("optimizers")
subdirs("orbitSim")
subdirs("pyBurstAnalysisGUI")
subdirs("pyExposure")
subdirs("pyLikelihood")
subdirs("rspgen")
subdirs("sane")
subdirs("sourceIdentify")
subdirs("SolarSystemTools")
subdirs("st_facilities")
subdirs("st_stream")
subdirs("st_graph")
subdirs("st_app")
subdirs("tip")
subdirs("timeSystem")
subdirs("xmlBase")
