# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.5.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

import typing
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _pyIrfLoader
else:
    import _pyIrfLoader

import builtins as __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pyIrfLoader.delete_SwigPyIterator

    def value(self):
        return _pyIrfLoader.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _pyIrfLoader.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _pyIrfLoader.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _pyIrfLoader.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _pyIrfLoader.SwigPyIterator_equal(self, x)

    def copy(self):
        return _pyIrfLoader.SwigPyIterator_copy(self)

    def __next__(self):
        return _pyIrfLoader.SwigPyIterator___next__(self)

    def previous(self):
        return _pyIrfLoader.SwigPyIterator_previous(self)

    def advance(self, n):
        return _pyIrfLoader.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _pyIrfLoader.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _pyIrfLoader.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _pyIrfLoader.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _pyIrfLoader.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _pyIrfLoader.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _pyIrfLoader.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _pyIrfLoader:
_pyIrfLoader.SwigPyIterator_swigregister(SwigPyIterator)
class DoublePair(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _pyIrfLoader.DoublePair_swiginit(self, _pyIrfLoader.new_DoublePair(*args))
    first = property(_pyIrfLoader.DoublePair_first_get, _pyIrfLoader.DoublePair_first_set)
    second = property(_pyIrfLoader.DoublePair_second_get, _pyIrfLoader.DoublePair_second_set)
    def __len__(self):
        return 2
    def __repr__(self):
        return str((self.first, self.second))
    def __getitem__(self, index): 
        if not (index % 2):
            return self.first
        else:
            return self.second
    def __setitem__(self, index, val):
        if not (index % 2):
            self.first = val
        else:
            self.second = val
    __swig_destroy__ = _pyIrfLoader.delete_DoublePair

# Register DoublePair in _pyIrfLoader:
_pyIrfLoader.DoublePair_swigregister(DoublePair)
class DoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _pyIrfLoader.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __bool__(self):
        return _pyIrfLoader.DoubleVector___bool__(self)

    def __len__(self):
        return _pyIrfLoader.DoubleVector___len__(self)

    def __delitem__(self, *args):
        return _pyIrfLoader.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyIrfLoader.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyIrfLoader.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _pyIrfLoader.DoubleVector_pop(self)

    def append(self, x):
        return _pyIrfLoader.DoubleVector_append(self, x)

    def empty(self):
        return _pyIrfLoader.DoubleVector_empty(self)

    def size(self):
        return _pyIrfLoader.DoubleVector_size(self)

    def swap(self, v):
        return _pyIrfLoader.DoubleVector_swap(self, v)

    def begin(self):
        return _pyIrfLoader.DoubleVector_begin(self)

    def end(self):
        return _pyIrfLoader.DoubleVector_end(self)

    def rbegin(self):
        return _pyIrfLoader.DoubleVector_rbegin(self)

    def rend(self):
        return _pyIrfLoader.DoubleVector_rend(self)

    def clear(self):
        return _pyIrfLoader.DoubleVector_clear(self)

    def get_allocator(self):
        return _pyIrfLoader.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _pyIrfLoader.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _pyIrfLoader.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        _pyIrfLoader.DoubleVector_swiginit(self, _pyIrfLoader.new_DoubleVector(*args))

    def push_back(self, x):
        return _pyIrfLoader.DoubleVector_push_back(self, x)

    def front(self):
        return _pyIrfLoader.DoubleVector_front(self)

    def back(self):
        return _pyIrfLoader.DoubleVector_back(self)

    def assign(self, n, x):
        return _pyIrfLoader.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _pyIrfLoader.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _pyIrfLoader.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _pyIrfLoader.DoubleVector_reserve(self, n)

    def capacity(self):
        return _pyIrfLoader.DoubleVector_capacity(self)
    __swig_destroy__ = _pyIrfLoader.delete_DoubleVector

# Register DoubleVector in _pyIrfLoader:
_pyIrfLoader.DoubleVector_swigregister(DoubleVector)
class StringVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _pyIrfLoader.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __bool__(self):
        return _pyIrfLoader.StringVector___bool__(self)

    def __len__(self):
        return _pyIrfLoader.StringVector___len__(self)

    def __delitem__(self, *args):
        return _pyIrfLoader.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyIrfLoader.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyIrfLoader.StringVector___setitem__(self, *args)

    def pop(self):
        return _pyIrfLoader.StringVector_pop(self)

    def append(self, x):
        return _pyIrfLoader.StringVector_append(self, x)

    def empty(self):
        return _pyIrfLoader.StringVector_empty(self)

    def size(self):
        return _pyIrfLoader.StringVector_size(self)

    def swap(self, v):
        return _pyIrfLoader.StringVector_swap(self, v)

    def begin(self):
        return _pyIrfLoader.StringVector_begin(self)

    def end(self):
        return _pyIrfLoader.StringVector_end(self)

    def rbegin(self):
        return _pyIrfLoader.StringVector_rbegin(self)

    def rend(self):
        return _pyIrfLoader.StringVector_rend(self)

    def clear(self):
        return _pyIrfLoader.StringVector_clear(self)

    def get_allocator(self):
        return _pyIrfLoader.StringVector_get_allocator(self)

    def pop_back(self):
        return _pyIrfLoader.StringVector_pop_back(self)

    def erase(self, *args):
        return _pyIrfLoader.StringVector_erase(self, *args)

    def __init__(self, *args):
        _pyIrfLoader.StringVector_swiginit(self, _pyIrfLoader.new_StringVector(*args))

    def push_back(self, x):
        return _pyIrfLoader.StringVector_push_back(self, x)

    def front(self):
        return _pyIrfLoader.StringVector_front(self)

    def back(self):
        return _pyIrfLoader.StringVector_back(self)

    def assign(self, n, x):
        return _pyIrfLoader.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _pyIrfLoader.StringVector_resize(self, *args)

    def insert(self, *args):
        return _pyIrfLoader.StringVector_insert(self, *args)

    def reserve(self, n):
        return _pyIrfLoader.StringVector_reserve(self, n)

    def capacity(self):
        return _pyIrfLoader.StringVector_capacity(self)
    __swig_destroy__ = _pyIrfLoader.delete_StringVector

# Register StringVector in _pyIrfLoader:
_pyIrfLoader.StringVector_swigregister(StringVector)
class IrfVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _pyIrfLoader.IrfVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __bool__(self):
        return _pyIrfLoader.IrfVector___bool__(self)

    def __len__(self):
        return _pyIrfLoader.IrfVector___len__(self)

    def __delitem__(self, *args):
        return _pyIrfLoader.IrfVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyIrfLoader.IrfVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyIrfLoader.IrfVector___setitem__(self, *args)

    def pop(self):
        return _pyIrfLoader.IrfVector_pop(self)

    def append(self, x):
        return _pyIrfLoader.IrfVector_append(self, x)

    def empty(self):
        return _pyIrfLoader.IrfVector_empty(self)

    def size(self):
        return _pyIrfLoader.IrfVector_size(self)

    def swap(self, v):
        return _pyIrfLoader.IrfVector_swap(self, v)

    def begin(self):
        return _pyIrfLoader.IrfVector_begin(self)

    def end(self):
        return _pyIrfLoader.IrfVector_end(self)

    def rbegin(self):
        return _pyIrfLoader.IrfVector_rbegin(self)

    def rend(self):
        return _pyIrfLoader.IrfVector_rend(self)

    def clear(self):
        return _pyIrfLoader.IrfVector_clear(self)

    def get_allocator(self):
        return _pyIrfLoader.IrfVector_get_allocator(self)

    def pop_back(self):
        return _pyIrfLoader.IrfVector_pop_back(self)

    def erase(self, *args):
        return _pyIrfLoader.IrfVector_erase(self, *args)

    def __init__(self, *args):
        _pyIrfLoader.IrfVector_swiginit(self, _pyIrfLoader.new_IrfVector(*args))

    def push_back(self, x):
        return _pyIrfLoader.IrfVector_push_back(self, x)

    def front(self):
        return _pyIrfLoader.IrfVector_front(self)

    def back(self):
        return _pyIrfLoader.IrfVector_back(self)

    def assign(self, n, x):
        return _pyIrfLoader.IrfVector_assign(self, n, x)

    def resize(self, *args):
        return _pyIrfLoader.IrfVector_resize(self, *args)

    def insert(self, *args):
        return _pyIrfLoader.IrfVector_insert(self, *args)

    def reserve(self, n):
        return _pyIrfLoader.IrfVector_reserve(self, n)

    def capacity(self):
        return _pyIrfLoader.IrfVector_capacity(self)
    __swig_destroy__ = _pyIrfLoader.delete_IrfVector

# Register IrfVector in _pyIrfLoader:
_pyIrfLoader.IrfVector_swigregister(IrfVector)
class ConeVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _pyIrfLoader.ConeVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __bool__(self):
        return _pyIrfLoader.ConeVector___bool__(self)

    def __len__(self):
        return _pyIrfLoader.ConeVector___len__(self)

    def __delitem__(self, *args):
        return _pyIrfLoader.ConeVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyIrfLoader.ConeVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyIrfLoader.ConeVector___setitem__(self, *args)

    def pop(self):
        return _pyIrfLoader.ConeVector_pop(self)

    def append(self, x):
        return _pyIrfLoader.ConeVector_append(self, x)

    def empty(self):
        return _pyIrfLoader.ConeVector_empty(self)

    def size(self):
        return _pyIrfLoader.ConeVector_size(self)

    def swap(self, v):
        return _pyIrfLoader.ConeVector_swap(self, v)

    def begin(self):
        return _pyIrfLoader.ConeVector_begin(self)

    def end(self):
        return _pyIrfLoader.ConeVector_end(self)

    def rbegin(self):
        return _pyIrfLoader.ConeVector_rbegin(self)

    def rend(self):
        return _pyIrfLoader.ConeVector_rend(self)

    def clear(self):
        return _pyIrfLoader.ConeVector_clear(self)

    def get_allocator(self):
        return _pyIrfLoader.ConeVector_get_allocator(self)

    def pop_back(self):
        return _pyIrfLoader.ConeVector_pop_back(self)

    def erase(self, *args):
        return _pyIrfLoader.ConeVector_erase(self, *args)

    def __init__(self, *args):
        _pyIrfLoader.ConeVector_swiginit(self, _pyIrfLoader.new_ConeVector(*args))

    def push_back(self, x):
        return _pyIrfLoader.ConeVector_push_back(self, x)

    def front(self):
        return _pyIrfLoader.ConeVector_front(self)

    def back(self):
        return _pyIrfLoader.ConeVector_back(self)

    def assign(self, n, x):
        return _pyIrfLoader.ConeVector_assign(self, n, x)

    def resize(self, *args):
        return _pyIrfLoader.ConeVector_resize(self, *args)

    def insert(self, *args):
        return _pyIrfLoader.ConeVector_insert(self, *args)

    def reserve(self, n):
        return _pyIrfLoader.ConeVector_reserve(self, n)

    def capacity(self):
        return _pyIrfLoader.ConeVector_capacity(self)
    __swig_destroy__ = _pyIrfLoader.delete_ConeVector

# Register ConeVector in _pyIrfLoader:
_pyIrfLoader.ConeVector_swigregister(ConeVector)
class Hep3Vector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    X = _pyIrfLoader.Hep3Vector_X
    Y = _pyIrfLoader.Hep3Vector_Y
    Z = _pyIrfLoader.Hep3Vector_Z
    NUM_COORDINATES = _pyIrfLoader.Hep3Vector_NUM_COORDINATES
    SIZE = _pyIrfLoader.Hep3Vector_SIZE

    def __init__(self, *args):
        _pyIrfLoader.Hep3Vector_swiginit(self, _pyIrfLoader.new_Hep3Vector(*args))
    __swig_destroy__ = _pyIrfLoader.delete_Hep3Vector

    def __call__(self, *args):
        return _pyIrfLoader.Hep3Vector___call__(self, *args)

    def x(self):
        return _pyIrfLoader.Hep3Vector_x(self)

    def y(self):
        return _pyIrfLoader.Hep3Vector_y(self)

    def z(self):
        return _pyIrfLoader.Hep3Vector_z(self)

    def setX(self, arg2):
        return _pyIrfLoader.Hep3Vector_setX(self, arg2)

    def setY(self, arg2):
        return _pyIrfLoader.Hep3Vector_setY(self, arg2)

    def setZ(self, arg2):
        return _pyIrfLoader.Hep3Vector_setZ(self, arg2)

    def set(self, x, y, z):
        return _pyIrfLoader.Hep3Vector_set(self, x, y, z)

    def phi(self):
        return _pyIrfLoader.Hep3Vector_phi(self)

    def mag2(self):
        return _pyIrfLoader.Hep3Vector_mag2(self)

    def mag(self):
        return _pyIrfLoader.Hep3Vector_mag(self)

    def setPhi(self, arg2):
        return _pyIrfLoader.Hep3Vector_setPhi(self, arg2)

    def setTheta(self, arg2):
        return _pyIrfLoader.Hep3Vector_setTheta(self, arg2)

    def setMag(self, arg2):
        return _pyIrfLoader.Hep3Vector_setMag(self, arg2)

    def setPerp(self, arg2):
        return _pyIrfLoader.Hep3Vector_setPerp(self, arg2)

    def setCylTheta(self, arg2):
        return _pyIrfLoader.Hep3Vector_setCylTheta(self, arg2)

    def perp2(self, *args):
        return _pyIrfLoader.Hep3Vector_perp2(self, *args)

    def perp(self, *args):
        return _pyIrfLoader.Hep3Vector_perp(self, *args)

    def __eq__(self, arg2):
        return _pyIrfLoader.Hep3Vector___eq__(self, arg2)

    def __ne__(self, arg2):
        return _pyIrfLoader.Hep3Vector___ne__(self, arg2)

    def isNear(self, *args):
        return _pyIrfLoader.Hep3Vector_isNear(self, *args)

    def howNear(self, v):
        return _pyIrfLoader.Hep3Vector_howNear(self, v)

    def deltaR(self, v):
        return _pyIrfLoader.Hep3Vector_deltaR(self, v)

    def __iadd__(self, arg2):
        return _pyIrfLoader.Hep3Vector___iadd__(self, arg2)

    def __isub__(self, arg2):
        return _pyIrfLoader.Hep3Vector___isub__(self, arg2)

    def __neg__(self):
        return _pyIrfLoader.Hep3Vector___neg__(self)

    def __itruediv__(self, *args):
        return _pyIrfLoader.Hep3Vector___itruediv__(self, *args)
    __idiv__ = __itruediv__



    def unit(self):
        return _pyIrfLoader.Hep3Vector_unit(self)

    def orthogonal(self):
        return _pyIrfLoader.Hep3Vector_orthogonal(self)

    def dot(self, arg2):
        return _pyIrfLoader.Hep3Vector_dot(self, arg2)

    def cross(self, arg2):
        return _pyIrfLoader.Hep3Vector_cross(self, arg2)

    def pseudoRapidity(self):
        return _pyIrfLoader.Hep3Vector_pseudoRapidity(self)

    def setEta(self, p):
        return _pyIrfLoader.Hep3Vector_setEta(self, p)

    def setCylEta(self, p):
        return _pyIrfLoader.Hep3Vector_setCylEta(self, p)

    def rotateX(self, arg2):
        return _pyIrfLoader.Hep3Vector_rotateX(self, arg2)

    def rotateY(self, arg2):
        return _pyIrfLoader.Hep3Vector_rotateY(self, arg2)

    def rotateZ(self, arg2):
        return _pyIrfLoader.Hep3Vector_rotateZ(self, arg2)

    def rotateUz(self, arg2):
        return _pyIrfLoader.Hep3Vector_rotateUz(self, arg2)

    def __imul__(self, *args):
        return _pyIrfLoader.Hep3Vector___imul__(self, *args)

    def transform(self, arg2):
        return _pyIrfLoader.Hep3Vector_transform(self, arg2)

    def setRThetaPhi(self, r, theta, phi):
        return _pyIrfLoader.Hep3Vector_setRThetaPhi(self, r, theta, phi)

    def setREtaPhi(self, r, eta, phi):
        return _pyIrfLoader.Hep3Vector_setREtaPhi(self, r, eta, phi)

    def setRhoPhiZ(self, rho, phi, z):
        return _pyIrfLoader.Hep3Vector_setRhoPhiZ(self, rho, phi, z)

    def setRhoPhiTheta(self, rho, phi, theta):
        return _pyIrfLoader.Hep3Vector_setRhoPhiTheta(self, rho, phi, theta)

    def setRhoPhiEta(self, rho, phi, eta):
        return _pyIrfLoader.Hep3Vector_setRhoPhiEta(self, rho, phi, eta)

    def getX(self):
        return _pyIrfLoader.Hep3Vector_getX(self)

    def getY(self):
        return _pyIrfLoader.Hep3Vector_getY(self)

    def getZ(self):
        return _pyIrfLoader.Hep3Vector_getZ(self)

    def getR(self):
        return _pyIrfLoader.Hep3Vector_getR(self)

    def getTheta(self):
        return _pyIrfLoader.Hep3Vector_getTheta(self)

    def getPhi(self):
        return _pyIrfLoader.Hep3Vector_getPhi(self)

    def r(self):
        return _pyIrfLoader.Hep3Vector_r(self)

    def rho(self):
        return _pyIrfLoader.Hep3Vector_rho(self)

    def getRho(self):
        return _pyIrfLoader.Hep3Vector_getRho(self)

    def getEta(self):
        return _pyIrfLoader.Hep3Vector_getEta(self)

    def setR(self, s):
        return _pyIrfLoader.Hep3Vector_setR(self, s)

    def setRho(self, s):
        return _pyIrfLoader.Hep3Vector_setRho(self, s)

    def compare(self, v):
        return _pyIrfLoader.Hep3Vector_compare(self, v)

    def __gt__(self, v):
        return _pyIrfLoader.Hep3Vector___gt__(self, v)

    def __lt__(self, v):
        return _pyIrfLoader.Hep3Vector___lt__(self, v)

    def __ge__(self, v):
        return _pyIrfLoader.Hep3Vector___ge__(self, v)

    def __le__(self, v):
        return _pyIrfLoader.Hep3Vector___le__(self, v)

    def diff2(self, v):
        return _pyIrfLoader.Hep3Vector_diff2(self, v)

    @staticmethod
    def setTolerance(tol):
        return _pyIrfLoader.Hep3Vector_setTolerance(tol)

    @staticmethod
    def getTolerance():
        return _pyIrfLoader.Hep3Vector_getTolerance()

    def isParallel(self, *args):
        return _pyIrfLoader.Hep3Vector_isParallel(self, *args)

    def isOrthogonal(self, *args):
        return _pyIrfLoader.Hep3Vector_isOrthogonal(self, *args)

    def howParallel(self, v):
        return _pyIrfLoader.Hep3Vector_howParallel(self, v)

    def howOrthogonal(self, v):
        return _pyIrfLoader.Hep3Vector_howOrthogonal(self, v)
    ToleranceTicks = _pyIrfLoader.Hep3Vector_ToleranceTicks

    def beta(self):
        return _pyIrfLoader.Hep3Vector_beta(self)

    def gamma(self):
        return _pyIrfLoader.Hep3Vector_gamma(self)

    def coLinearRapidity(self):
        return _pyIrfLoader.Hep3Vector_coLinearRapidity(self)

    def angle(self, *args):
        return _pyIrfLoader.Hep3Vector_angle(self, *args)

    def theta(self, *args):
        return _pyIrfLoader.Hep3Vector_theta(self, *args)

    def cosTheta(self, *args):
        return _pyIrfLoader.Hep3Vector_cosTheta(self, *args)

    def cos2Theta(self, *args):
        return _pyIrfLoader.Hep3Vector_cos2Theta(self, *args)

    def project(self, *args):
        return _pyIrfLoader.Hep3Vector_project(self, *args)

    def perpPart(self, *args):
        return _pyIrfLoader.Hep3Vector_perpPart(self, *args)

    def rapidity(self, *args):
        return _pyIrfLoader.Hep3Vector_rapidity(self, *args)

    def eta(self, *args):
        return _pyIrfLoader.Hep3Vector_eta(self, *args)

    def deltaPhi(self, v2):
        return _pyIrfLoader.Hep3Vector_deltaPhi(self, v2)

    def polarAngle(self, *args):
        return _pyIrfLoader.Hep3Vector_polarAngle(self, *args)

    def azimAngle(self, *args):
        return _pyIrfLoader.Hep3Vector_azimAngle(self, *args)

    def rotate(self, *args):
        return _pyIrfLoader.Hep3Vector_rotate(self, *args)

# Register Hep3Vector in _pyIrfLoader:
_pyIrfLoader.Hep3Vector_swigregister(Hep3Vector)

def rotationXOf(vec, delta):
    return _pyIrfLoader.rotationXOf(vec, delta)

def rotationYOf(vec, delta):
    return _pyIrfLoader.rotationYOf(vec, delta)

def rotationZOf(vec, delta):
    return _pyIrfLoader.rotationZOf(vec, delta)

def rotationOf(*args):
    return _pyIrfLoader.rotationOf(*args)

def __lshift__(arg1, arg2):
    return _pyIrfLoader.__lshift__(arg1, arg2)

def __rshift__(arg1, arg2):
    return _pyIrfLoader.__rshift__(arg1, arg2)

def __truediv__(arg1, a):
    return _pyIrfLoader.__truediv__(arg1, a)

def __add__(arg1, arg2):
    return _pyIrfLoader.__add__(arg1, arg2)

def __sub__(arg1, arg2):
    return _pyIrfLoader.__sub__(arg1, arg2)

def __mul__(*args):
    return _pyIrfLoader.__mul__(*args)
ASTRO_D2R = _pyIrfLoader.ASTRO_D2R
ASTRO_R2D = _pyIrfLoader.ASTRO_R2D
ASTRO_PIOVER2 = _pyIrfLoader.ASTRO_PIOVER2
ASTRO_4PI = _pyIrfLoader.ASTRO_4PI

def degToRad(deg):
    return _pyIrfLoader.degToRad(deg)

def radToDeg(rad):
    return _pyIrfLoader.radToDeg(rad)

def latToTheta_Deg(lat):
    return _pyIrfLoader.latToTheta_Deg(lat)

def thetaToLat_Deg(theta):
    return _pyIrfLoader.thetaToLat_Deg(theta)

def latToTheta_Rad(lat):
    return _pyIrfLoader.latToTheta_Rad(lat)

def thetaToLat_Rad(theta):
    return _pyIrfLoader.thetaToLat_Rad(theta)
class ProjBase(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    WCS = _pyIrfLoader.ProjBase_WCS
    HEALPIX = _pyIrfLoader.ProjBase_HEALPIX
    UNKNOWN = _pyIrfLoader.ProjBase_UNKNOWN
    __swig_destroy__ = _pyIrfLoader.delete_ProjBase

    def clone(self):
        return _pyIrfLoader.ProjBase_clone(self)

    def sph2pix(self, s1, s2):
        return _pyIrfLoader.ProjBase_sph2pix(self, s1, s2)

    def pix2pix(self, x1, x2, otherProjection):
        return _pyIrfLoader.ProjBase_pix2pix(self, x1, x2, otherProjection)

    def pix2sph(self, x1, x2):
        return _pyIrfLoader.ProjBase_pix2sph(self, x1, x2)

    def isGalactic(self):
        return _pyIrfLoader.ProjBase_isGalactic(self)

    def projType(self):
        return _pyIrfLoader.ProjBase_projType(self)

    def method(self):
        return _pyIrfLoader.ProjBase_method(self)

    def range(self, x1, xvar):
        return _pyIrfLoader.ProjBase_range(self, x1, xvar)

    def testpix2sph(self, x1, x2):
        return _pyIrfLoader.ProjBase_testpix2sph(self, x1, x2)

    def setKeywords(self, header):
        return _pyIrfLoader.ProjBase_setKeywords(self, header)

# Register ProjBase in _pyIrfLoader:
_pyIrfLoader.ProjBase_swigregister(ProjBase)
cvar = _pyIrfLoader.cvar
HepXHat = cvar.HepXHat
HepYHat = cvar.HepYHat
HepZHat = cvar.HepZHat

class SkyProj(ProjBase):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _pyIrfLoader.delete_SkyProj

    def __init__(self, *args):
        _pyIrfLoader.SkyProj_swiginit(self, _pyIrfLoader.new_SkyProj(*args))

    def clone(self):
        return _pyIrfLoader.SkyProj_clone(self)

    def sph2pix(self, s1, s2):
        return _pyIrfLoader.SkyProj_sph2pix(self, s1, s2)

    def pix2pix(self, x1, x2, otherProjection):
        return _pyIrfLoader.SkyProj_pix2pix(self, x1, x2, otherProjection)

    def pix2sph(self, x1, x2):
        return _pyIrfLoader.SkyProj_pix2sph(self, x1, x2)

    def range(self, x1, xvar):
        return _pyIrfLoader.SkyProj_range(self, x1, xvar)

    def testpix2sph(self, x1, x2):
        return _pyIrfLoader.SkyProj_testpix2sph(self, x1, x2)

    def setKeywords(self, header):
        return _pyIrfLoader.SkyProj_setKeywords(self, header)

# Register SkyProj in _pyIrfLoader:
_pyIrfLoader.SkyProj_swigregister(SkyProj)
class HealpixProj(ProjBase):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _pyIrfLoader.delete_HealpixProj

    def __init__(self, *args):
        _pyIrfLoader.HealpixProj_swiginit(self, _pyIrfLoader.new_HealpixProj(*args))

    def clone(self):
        return _pyIrfLoader.HealpixProj_clone(self)

    def sph2pix(self, s1, s2):
        return _pyIrfLoader.HealpixProj_sph2pix(self, s1, s2)

    def pix2pix(self, x1, x2, otherProjection):
        return _pyIrfLoader.HealpixProj_pix2pix(self, x1, x2, otherProjection)

    def pix2sph(self, x1, x2):
        return _pyIrfLoader.HealpixProj_pix2sph(self, x1, x2)

    def range(self, x1, xvar):
        return _pyIrfLoader.HealpixProj_range(self, x1, xvar)

    def testpix2sph(self, x1, x2):
        return _pyIrfLoader.HealpixProj_testpix2sph(self, x1, x2)

    def setKeywords(self, header):
        return _pyIrfLoader.HealpixProj_setKeywords(self, header)

    def healpix(self):
        return _pyIrfLoader.HealpixProj_healpix(self)

    def convertToPointing(self, dir):
        return _pyIrfLoader.HealpixProj_convertToPointing(self, dir)

# Register HealpixProj in _pyIrfLoader:
_pyIrfLoader.HealpixProj_swigregister(HealpixProj)
class SkyDir(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    GALACTIC = _pyIrfLoader.SkyDir_GALACTIC
    EQUATORIAL = _pyIrfLoader.SkyDir_EQUATORIAL

    def __init__(self, *args):
        _pyIrfLoader.SkyDir_swiginit(self, _pyIrfLoader.new_SkyDir(*args))

    def __call__(self, *args):
        return _pyIrfLoader.SkyDir___call__(self, *args)

    def l(self):
        return _pyIrfLoader.SkyDir_l(self)

    def b(self):
        return _pyIrfLoader.SkyDir_b(self)

    def ra(self):
        return _pyIrfLoader.SkyDir_ra(self)

    def dec(self):
        return _pyIrfLoader.SkyDir_dec(self)

    def dir(self):
        return _pyIrfLoader.SkyDir_dir(self)

    def difference(self, other):
        return _pyIrfLoader.SkyDir_difference(self, other)

    def project(self, projection):
        return _pyIrfLoader.SkyDir_project(self, projection)

    def isValid(self):
        return _pyIrfLoader.SkyDir_isValid(self)

    def zenithCoords(self, zenithDir):
        return _pyIrfLoader.SkyDir_zenithCoords(self, zenithDir)

    def cross(self, *args):
        return _pyIrfLoader.SkyDir_cross(self, *args)

    def dot(self, *args):
        return _pyIrfLoader.SkyDir_dot(self, *args)
    __swig_destroy__ = _pyIrfLoader.delete_SkyDir

# Register SkyDir in _pyIrfLoader:
_pyIrfLoader.SkyDir_swigregister(SkyDir)
class AcceptanceCone(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _pyIrfLoader.AcceptanceCone_swiginit(self, _pyIrfLoader.new_AcceptanceCone(*args))

    def center(self):
        return _pyIrfLoader.AcceptanceCone_center(self)

    def radius(self):
        return _pyIrfLoader.AcceptanceCone_radius(self)

    def __eq__(self, rhs):
        return _pyIrfLoader.AcceptanceCone___eq__(self, rhs)

    def __ne__(self, rhs):
        return _pyIrfLoader.AcceptanceCone___ne__(self, rhs)

    def inside(self, dir):
        return _pyIrfLoader.AcceptanceCone_inside(self, dir)

    def clone(self):
        return _pyIrfLoader.AcceptanceCone_clone(self)
    __swig_destroy__ = _pyIrfLoader.delete_AcceptanceCone

# Register AcceptanceCone in _pyIrfLoader:
_pyIrfLoader.AcceptanceCone_swigregister(AcceptanceCone)
class IAeff(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pyIrfLoader.delete_IAeff

    def value(self, *args):
        return _pyIrfLoader.IAeff_value(self, *args)

    def __call__(self, energy, srcDir, scZAxis, scXAxis, time=0):
        return _pyIrfLoader.IAeff___call__(self, energy, srcDir, scZAxis, scXAxis, time)

    def clone(self):
        return _pyIrfLoader.IAeff_clone(self)

    def upperLimit(self):
        return _pyIrfLoader.IAeff_upperLimit(self)

    def setPhiDependence(self, usePhiDependence):
        return _pyIrfLoader.IAeff_setPhiDependence(self, usePhiDependence)

    def usePhiDependence(self):
        return _pyIrfLoader.IAeff_usePhiDependence(self)

# Register IAeff in _pyIrfLoader:
_pyIrfLoader.IAeff_swigregister(IAeff)
class IPsf(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pyIrfLoader.delete_IPsf

    def __call__(self, appDir, energy, srcDir, scZAxis, scXAxis, time=0):
        return _pyIrfLoader.IPsf___call__(self, appDir, energy, srcDir, scZAxis, scXAxis, time)

    def angularIntegral(self, *args):
        return _pyIrfLoader.IPsf_angularIntegral(self, *args)

    def angularContainment(self, *args):
        return _pyIrfLoader.IPsf_angularContainment(self, *args)

    def appDir(self, energy, srcDir, scZAxis, scXAxis, time=0):
        return _pyIrfLoader.IPsf_appDir(self, energy, srcDir, scZAxis, scXAxis, time)

    def clone(self):
        return _pyIrfLoader.IPsf_clone(self)

    @staticmethod
    def psfIntegral(*args):
        return _pyIrfLoader.IPsf_psfIntegral(*args)

    def app_dir(self, energy, inclination):
        return _pyIrfLoader.IPsf_app_dir(self, energy, inclination)

    def value(self, *args):
        return _pyIrfLoader.IPsf_value(self, *args)

# Register IPsf in _pyIrfLoader:
_pyIrfLoader.IPsf_swigregister(IPsf)
class IEdisp(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pyIrfLoader.delete_IEdisp

    def __call__(self, appEnergy, energy, srcDir, scZAxis, scXAxis, time=0):
        return _pyIrfLoader.IEdisp___call__(self, appEnergy, energy, srcDir, scZAxis, scXAxis, time)

    def appEnergy(self, energy, srcDir, scZAxis, scXAxis, time=0):
        return _pyIrfLoader.IEdisp_appEnergy(self, energy, srcDir, scZAxis, scXAxis, time)

    def integral(self, *args):
        return _pyIrfLoader.IEdisp_integral(self, *args)

    def meanAppEnergy(self, *args):
        return _pyIrfLoader.IEdisp_meanAppEnergy(self, *args)

    def meanTrueEnergy(self, *args):
        return _pyIrfLoader.IEdisp_meanTrueEnergy(self, *args)

    def clone(self):
        return _pyIrfLoader.IEdisp_clone(self)

    def value(self, *args):
        return _pyIrfLoader.IEdisp_value(self, *args)

# Register IEdisp in _pyIrfLoader:
_pyIrfLoader.IEdisp_swigregister(IEdisp)
class IEfficiencyFactor(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pyIrfLoader.delete_IEfficiencyFactor

    def __call__(self, energy, met):
        return _pyIrfLoader.IEfficiencyFactor___call__(self, energy, met)

    def value(self, *args):
        return _pyIrfLoader.IEfficiencyFactor_value(self, *args)

    def getLivetimeFactors(self, energy, factor1, factor2, met=0):
        return _pyIrfLoader.IEfficiencyFactor_getLivetimeFactors(self, energy, factor1, factor2, met)

    def clone(self):
        return _pyIrfLoader.IEfficiencyFactor_clone(self)

    def readFt2File(self, ft2file):
        return _pyIrfLoader.IEfficiencyFactor_readFt2File(self, ft2file)

    def clearFt2Data(self):
        return _pyIrfLoader.IEfficiencyFactor_clearFt2Data(self)

# Register IEfficiencyFactor in _pyIrfLoader:
_pyIrfLoader.IEfficiencyFactor_swigregister(IEfficiencyFactor)
class Irfs(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _pyIrfLoader.Irfs_swiginit(self, _pyIrfLoader.new_Irfs(*args))
    __swig_destroy__ = _pyIrfLoader.delete_Irfs

    def aeff(self):
        return _pyIrfLoader.Irfs_aeff(self)

    def psf(self):
        return _pyIrfLoader.Irfs_psf(self)

    def edisp(self):
        return _pyIrfLoader.Irfs_edisp(self)

    def efficiencyFactor(self):
        return _pyIrfLoader.Irfs_efficiencyFactor(self)

    def setEfficiencyFactor(self, eff):
        return _pyIrfLoader.Irfs_setEfficiencyFactor(self, eff)

    def setAeff(self, aeff):
        return _pyIrfLoader.Irfs_setAeff(self, aeff)

    def setPsf(self, psf):
        return _pyIrfLoader.Irfs_setPsf(self, psf)

    def setEdisp(self, edisp):
        return _pyIrfLoader.Irfs_setEdisp(self, edisp)

    def clone(self):
        return _pyIrfLoader.Irfs_clone(self)

    def irfID(self):
        return _pyIrfLoader.Irfs_irfID(self)

    def setIrfID(self, irfID):
        return _pyIrfLoader.Irfs_setIrfID(self, irfID)

# Register Irfs in _pyIrfLoader:
_pyIrfLoader.Irfs_swigregister(Irfs)
class IrfsFactory(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def create(self, name):
        return _pyIrfLoader.IrfsFactory_create(self, name)

    def addIrfs(self, name, irfs, verbose=False):
        return _pyIrfLoader.IrfsFactory_addIrfs(self, name, irfs, verbose)

    def getIrfsNames(self, names):
        return _pyIrfLoader.IrfsFactory_getIrfsNames(self, names)

    @staticmethod
    def instance():
        return _pyIrfLoader.IrfsFactory_instance()

    @staticmethod
    def delete_instance():
        return _pyIrfLoader.IrfsFactory_delete_instance()

    def irfNames(self, *args):
        return _pyIrfLoader.IrfsFactory_irfNames(self, *args)

# Register IrfsFactory in _pyIrfLoader:
_pyIrfLoader.IrfsFactory_swigregister(IrfsFactory)
class Loader(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def go(*args):
        return _pyIrfLoader.Loader_go(*args)

    @staticmethod
    def respIds():
        return _pyIrfLoader.Loader_respIds()

# Register Loader in _pyIrfLoader:
_pyIrfLoader.Loader_swigregister(Loader)
class Bilinear(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, x, y, values, xlo, xhi, ylo, yhi):
        _pyIrfLoader.Bilinear_swiginit(self, _pyIrfLoader.new_Bilinear(x, y, values, xlo, xhi, ylo, yhi))

    def __call__(self, x, y):
        return _pyIrfLoader.Bilinear___call__(self, x, y)

    def getCorners(self, x, y, tt, uu, corner_xvals, corner_yvals, zvals):
        return _pyIrfLoader.Bilinear_getCorners(self, x, y, tt, uu, corner_xvals, corner_yvals, zvals)

    @staticmethod
    def evaluate(tt, uu, zvals):
        return _pyIrfLoader.Bilinear_evaluate(tt, uu, zvals)

    def getPar(self, i, j):
        return _pyIrfLoader.Bilinear_getPar(self, i, j)

    def setPar(self, i, j, value):
        return _pyIrfLoader.Bilinear_setPar(self, i, j, value)
    __swig_destroy__ = _pyIrfLoader.delete_Bilinear

# Register Bilinear in _pyIrfLoader:
_pyIrfLoader.Bilinear_swigregister(Bilinear)
class ParTables(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _pyIrfLoader.ParTables_swiginit(self, _pyIrfLoader.new_ParTables(*args))

    def parNames(self):
        return _pyIrfLoader.ParTables_parNames(self)

    def getParVector(self, parName, pars):
        return _pyIrfLoader.ParTables_getParVector(self, parName, pars)

    def getCornerPars(self, logE, costh, tt, uu, cornerEnergies, parVectors):
        return _pyIrfLoader.ParTables_getCornerPars(self, logE, costh, tt, uu, cornerEnergies, parVectors)

    def logEnergies(self):
        return _pyIrfLoader.ParTables_logEnergies(self)

    def costhetas(self):
        return _pyIrfLoader.ParTables_costhetas(self)

    def ebounds(self):
        return _pyIrfLoader.ParTables_ebounds(self)

    def tbounds(self):
        return _pyIrfLoader.ParTables_tbounds(self)

    def getPars(self, *args):
        return _pyIrfLoader.ParTables_getPars(self, *args)

    def setPars(self, ilogE, icosth, pars):
        return _pyIrfLoader.ParTables_setPars(self, ilogE, icosth, pars)

    def params(self, indx):
        return _pyIrfLoader.ParTables_params(self, indx)

    def setParams(self, indx, params):
        return _pyIrfLoader.ParTables_setParams(self, indx, params)
    __swig_destroy__ = _pyIrfLoader.delete_ParTables

# Register ParTables in _pyIrfLoader:
_pyIrfLoader.ParTables_swigregister(ParTables)
class Aeff(IAeff):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _pyIrfLoader.Aeff_swiginit(self, _pyIrfLoader.new_Aeff(*args))
    __swig_destroy__ = _pyIrfLoader.delete_Aeff

    def value(self, *args):
        return _pyIrfLoader.Aeff_value(self, *args)

    def clone(self):
        return _pyIrfLoader.Aeff_clone(self)

    def upperLimit(self):
        return _pyIrfLoader.Aeff_upperLimit(self)

    def max_phi_modulation(self):
        return _pyIrfLoader.Aeff_max_phi_modulation(self)

    def pars(self, logE, costh, interpolate=False):
        return _pyIrfLoader.Aeff_pars(self, logE, costh, interpolate)

    def phi_modulation(self, logE, costheta, phi, interpolate):
        return _pyIrfLoader.Aeff_phi_modulation(self, logE, costheta, phi, interpolate)

    def logEnergies(self):
        return _pyIrfLoader.Aeff_logEnergies(self)

    def costhetas(self):
        return _pyIrfLoader.Aeff_costhetas(self)

    def values(self):
        return _pyIrfLoader.Aeff_values(self)

    def setValues(self, values):
        return _pyIrfLoader.Aeff_setValues(self, values)

    @staticmethod
    def cast(iaeff):
        return _pyIrfLoader.Aeff_cast(iaeff)

# Register Aeff in _pyIrfLoader:
_pyIrfLoader.Aeff_swigregister(Aeff)
class PsfBase(IPsf):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pyIrfLoader.delete_PsfBase

    def scaleFactor(self, energy, isFront):
        return _pyIrfLoader.PsfBase_scaleFactor(self, energy, isFront)

# Register PsfBase in _pyIrfLoader:
_pyIrfLoader.PsfBase_swigregister(PsfBase)
class Psf3(PsfBase):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _pyIrfLoader.Psf3_swiginit(self, _pyIrfLoader.new_Psf3(*args))
    __swig_destroy__ = _pyIrfLoader.delete_Psf3

    def value(self, *args):
        return _pyIrfLoader.Psf3_value(self, *args)

    def angularIntegral(self, *args):
        return _pyIrfLoader.Psf3_angularIntegral(self, *args)

    def nparams(self):
        return _pyIrfLoader.Psf3_nparams(self)

    def params(self, indx):
        return _pyIrfLoader.Psf3_params(self, indx)

    def energies(self):
        return _pyIrfLoader.Psf3_energies(self)

    def logEnergies(self):
        return _pyIrfLoader.Psf3_logEnergies(self)

    def costhetas(self):
        return _pyIrfLoader.Psf3_costhetas(self)

    def thetas(self):
        return _pyIrfLoader.Psf3_thetas(self)

    def clone(self):
        return _pyIrfLoader.Psf3_clone(self)

    def setParams(self, indx, params):
        return _pyIrfLoader.Psf3_setParams(self, indx, params)

    @staticmethod
    def findIndex(xx, x):
        return _pyIrfLoader.Psf3_findIndex(xx, x)

    @staticmethod
    def cast(ipsf):
        return _pyIrfLoader.Psf3_cast(ipsf)

# Register Psf3 in _pyIrfLoader:
_pyIrfLoader.Psf3_swigregister(Psf3)
class EdispInterpolator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, fitsfile, extname, nrow):
        _pyIrfLoader.EdispInterpolator_swiginit(self, _pyIrfLoader.new_EdispInterpolator(fitsfile, extname, nrow))
    __swig_destroy__ = _pyIrfLoader.delete_EdispInterpolator

    def fitsfile(self):
        return _pyIrfLoader.EdispInterpolator_fitsfile(self)

    def extname(self):
        return _pyIrfLoader.EdispInterpolator_extname(self)

    def nrow(self):
        return _pyIrfLoader.EdispInterpolator_nrow(self)

    def nparams(self):
        return _pyIrfLoader.EdispInterpolator_nparams(self)

    def params(self, indx):
        return _pyIrfLoader.EdispInterpolator_params(self, indx)

    def energies(self):
        return _pyIrfLoader.EdispInterpolator_energies(self)

    def logEnergies(self):
        return _pyIrfLoader.EdispInterpolator_logEnergies(self)

    def costhetas(self):
        return _pyIrfLoader.EdispInterpolator_costhetas(self)

    def thetas(self):
        return _pyIrfLoader.EdispInterpolator_thetas(self)

    def setParams(self, indx, params):
        return _pyIrfLoader.EdispInterpolator_setParams(self, indx, params)

# Register EdispInterpolator in _pyIrfLoader:
_pyIrfLoader.EdispInterpolator_swigregister(EdispInterpolator)
class Edisp3(IEdisp):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _pyIrfLoader.Edisp3_swiginit(self, _pyIrfLoader.new_Edisp3(*args))
    __swig_destroy__ = _pyIrfLoader.delete_Edisp3

    def value(self, *args):
        return _pyIrfLoader.Edisp3_value(self, *args)

    def clone(self):
        return _pyIrfLoader.Edisp3_clone(self)

    def scaleFactor(self, energy, costheta):
        return _pyIrfLoader.Edisp3_scaleFactor(self, energy, costheta)

    def evaluate(self, emeas, energy, theta, phi, time, pars):
        return _pyIrfLoader.Edisp3_evaluate(self, emeas, energy, theta, phi, time, pars)

    def renormalize(self, logE, costh, params):
        return _pyIrfLoader.Edisp3_renormalize(self, logE, costh, params)

    def interpolator(self):
        return _pyIrfLoader.Edisp3_interpolator(self)

    def nparams(self):
        return _pyIrfLoader.Edisp3_nparams(self)

    def params(self, indx):
        return _pyIrfLoader.Edisp3_params(self, indx)

    def energies(self):
        return _pyIrfLoader.Edisp3_energies(self)

    def logEnergies(self):
        return _pyIrfLoader.Edisp3_logEnergies(self)

    def costhetas(self):
        return _pyIrfLoader.Edisp3_costhetas(self)

    def thetas(self):
        return _pyIrfLoader.Edisp3_thetas(self)

    def parTables(self):
        return _pyIrfLoader.Edisp3_parTables(self)

    def setParams(self, indx, params):
        return _pyIrfLoader.Edisp3_setParams(self, indx, params)

    @staticmethod
    def cast(iedisp):
        return _pyIrfLoader.Edisp3_cast(iedisp)

# Register Edisp3 in _pyIrfLoader:
_pyIrfLoader.Edisp3_swigregister(Edisp3)

