name: Build the Conda package
on:
  workflow_call:
    inputs:
      matrix_json:
        required: true
        type: string
        description: "JSON string representing the matrix"
      build_label:
        required: true
        type: string
        description: "Fermitools package build label"
    outputs:
      pkg_ver:
        description: "The Fermitools conda package version"
        value: ${{ jobs.build-conda.outputs.fermitools-pkg }}

jobs:
  build-conda:
    name: "${{matrix.os}} ${{matrix.arch}} ${{matrix.container}}"
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    defaults:
      run:
        shell: bash -el {0}
    outputs:
      fermitools-pkg: ${{env.FERMITOOLS_VERSION }}
    continue-on-error: true # Default false is to fail at first error
    strategy:
      matrix: ${{ fromJson(inputs.matrix_json) }}
    steps:
      - name: Run environment-specific commands
        id: get_git_safe_dir
        run: |
          if [[ "${{ matrix.os }}" =~ "macos-" && "${{ matrix.arch }}" == "x86_64" ]]; then
            echo "Setting MacOS x86 env var" # debug
            echo "MACOS_ARCH=x86" >> "$GITHUB_ENV"
          fi
          if [[ "${{ matrix.os }}" =~ "ubuntu-" && "${{ matrix.arch }}" == "x86" ]]; then
            yum -y install git jq python3
            git config --global --add safe.directory /__w/ScienceTools/ScienceTools
            GIT_SAFE_DIRECTORY=$(git config --global --get safe.directory)
            echo "The global Git safe is: $GIT_SAFE_DIRECTORY"
            echo "git_safe_dir=$GIT_SAFE_DIRECTORY" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }} # reset_checkout_fixes checkout_fixes  master
          submodules: 'recursive' # true
          # fetch-depth: 0 # Fetches full history

      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v4
        with:
          conda-remove-defaults: true
          python-version: 3.12
          environment-file: environments/${{matrix.env_target_file}}    # environments/fermitools-develop-osx.yml or fermitools-develop-linux.yml
          auto-update-conda: true
          auto-activate-base: false
          show-channel-urls: true

      - name: Increment version number
        run: |
          if [[ "${{ steps.get_git_safe_dir.outputs.git_safe_dir }}" != ""  ]]; then
            echo "github.safe.directory exists"
            ls -l ${{ steps.get_git_safe_dir.outputs.git_safe_dir }}
            source ${{ steps.get_git_safe_dir.outputs.git_safe_dir }}/recipe/increment_fermi_version.sh
          else
            echo "github.xyz does not exist"
            ls -l ${{ github.workspace }}
            source ${{ github.workspace }}/recipe/increment_fermi_version.sh
          fi 
          echo "FERMITOOLS_VERSION=$FERMITOOLS_VERSION" >> "$GITHUB_ENV"
          echo " COE ${{vars.CONTINUE_ON_ERROR }} "
        env:
           LABEL_BUILD: ${{ inputs.build_label }} # dev


      - name: Build and upload the conda packages
        id: conda-build-and-upload
        # Runs the action with the following inputs or defaults if not specified.
        uses: cascode-labs/build-conda-action@v0.1.4
        with:
          recipe_path: recipe
          build_options: ' -c conda-forge -c fermi'
