name: CMake Build
on:
  push:
    branches: [ 'addition_creator_fits' ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  docker:
    runs-on: ubuntu-22.04 # Or windows-latest, macos-latest
    defaults:
     run:
        shell: bash -el {0}
    steps:
    - name: checkout the code
      uses: actions/checkout@v4 # Checkout the repository code
      with:
        submodules: 'recursive'

    - name: Get miniforge
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environments/fermitools-develop-linux.yml
        environment-name: fermi-dev
        init-shell: bash
        cache-environment: true
        ## post-cleanup: 'all'

    - name: Install CMake and Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential curl # For Ubuntu/Debian

    - name: Configure CMake
      run: cmake -S . -B RelWithDebInfo -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_VERBOSE_MAKEFILE=ON  -DCMAKE_INSTALL_PREFIX="$CONDA_PREFIX" -DCMAKE_PREFIX_PATH="$CONDA_PREFIX"

    - name: Build Project
      run: cmake --build RelWithDebInfo --target=install
