name: Conda CICD 

on:
  push:
    branches: ['master']
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  conda_deployment:
    name: Conda deployment
    # runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build-type: ['Release']
        include:
          - os: ubuntu-22.04-arm
            arch: arm64
            env_target_file: "fermitools-develop-linux.yml"
          - os: ubuntu-22.04
            arch: x86
            container: redhat/ubi8:latest
            env_target_file: "fermitools-develop-linux.yml"
          - os: macos-13
            arch: x86_64
            env_target_file: "fermitools-develop-osx-x86.yml"
            packages: llvm cfitsio swig
          - os: macos-15 # arm64
            arch: arm64
            env_target_file: "fermitools-develop-osx-arm64.yml"
            packages: llvm cfitsio swig
    uses: ./.github/workflows/build_conda.yaml
    with:
      build-type: ${{matrix.build-type}}
      os: ${{matrix.os}}
      build-arch: ${{matrix.arch}}
      build-packages: ${{matrix.packages}}
      build-env-target: ${{matrix.env_target_file}}
    secrets: inherit
