name: CMake Build
on:
  push:
    branches: [ 'addition_creator_fits' ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  docker:
    runs-on: ubuntu-latest # Or windows-latest, macos-latest

    steps:
    - name: Setup curl
      uses: kordlib/setup-curl@v1.0.2
    - name: checkout the code 
      uses: actions/checkout@v4 # Checkout the repository code
    - name: Get miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Miniforge3
        activate-environment: fermi-dev
        environment-file: environments/fermitools-develop-linux.yml

    - name: Install CMake and Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential # For Ubuntu/Debian

    - name: Configure CMake
      run: cmake -S . -B RelWithDebInfo -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="$CONDA_PREFIX" -DCMAKE_PREFIX_PATH="$CONDA_PREFIX"

    - name: Build Project
      run: cmake --build RelWithDebInfo --target=install
