name: Cleanup GHA Caches
on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write # Required to delete caches
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Delete all caches
        run: |
          # Max 30 items: gh cache delete --all
          gh cache list --limit 1000 --json id --jq '.[] | .id' | xargs -I {} gh cache delete {}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
