name: Generate Matrix
on:
  workflow_call:
    outputs:
      matrix:
        description: "JSON array of matrix values"
        value: ${{ jobs.generate.outputs.matrix }}

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - id: set_matrix
        run: |
          MATRIX_VALUES='[
            {"os": "ubuntu-24.04-arm", "arch": "arm64", "env_target_file": "fermitools-develop-linux.yml"},
            {"os": "ubuntu-24.04", "arch": "x86", "env_target_file": "fermitools-develop-linux.yml"},
            {"os": "macos-13", "arch": "x86_64", "env_target_file": "fermitools-develop-osx-x86.yml", "packages": "llvm cfitsio swig"},
            {"os": "macos-15", "arch": "arm64", "env_target_file": "fermitools-develop-osx-arm64.yml", "packages": "llvm cfitsio swig"}
          ]'
          echo "matrix=$MATRIX_VALUES" >> "$GITHUB_OUTPUT"
