name: Generate Matrix
on:
  workflow_call:
    outputs:
      matrix:
        description: "JSON array of matrix values"
        value: ${{ jobs.generate-matrix.outputs.matrix }}

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - id: set_matrix
        run: |
          MATRIX_VALUES='
          {"os": "ubuntu-24.04-arm", "arch": "arm64", "env_target_file": "fermitools-develop-linux.yml"},
          {"os": "ubuntu-24.04", "arch": "x86", "env_target_file": "fermitools-develop-linux.yml"}
          ' 
          # echo ut name=matrix-combinations::{\"include\":[$MATRIX_PARAMS_COMBINATIONS]}
          echo "matrix={\"include\":[$MATRIX_VALUES]}" >> "$GITHUB_OUTPUT"

  matrix-job:
    runs-on: ubuntu-latest
    needs: generate-matrix 
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - run: |
          # Prove things are set
          echo os=${{ matrix.os }}
          echo arch=${{ matrix.arch }}
          echo env=${{ matrix.env_target_file }}
