name: Generate Fermitools OS Matrix
on:
  workflow_call:
    outputs:
      matrix:
        description: "JSON array of matrix values"
        value: ${{ jobs.generate-matrix.outputs.matrix }}

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    # List of OSes, architecture, file containing Python dependencies, and additional packages needed to be installed.
    # Both OSes now use only one environment file since the Python dependencies are the same.
    steps:
      - id: set_matrix
        run: |
          MATRIX_VALUES='{"os": "ubuntu-24.04-arm", "arch": "arm64", "env_target_file": "fermitools-develop-linux.yml"}, {"os": "ubuntu-24.04", "arch": "x86", "env_target_file": "fermitools-develop-linux.yml"}, {"os": "macos-15-intel", "arch": "x86_64", "env_target_file": "fermitools-develop-osx.yml", "packages": "llvm cfitsio swig"}, {"os": "macos-15", "arch": "arm64", "env_target_file": "fermitools-develop-osx.yml", "packages": "llvm cfitsio swig"}' 
          echo "matrix={\"include\":[$MATRIX_VALUES]}" >> "$GITHUB_OUTPUT"
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
