name: Build and upload conda packages

on:
  push:
    branches: checkout_fixes
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
jobs:
  conda_deployment:
    name: Conda deployment
    runs-on: ${{ matrix.os }}
    defaults:
     run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04-arm
            arch: arm64
            env_target_file: "fermitools-develop-linux.yml"
          - os: ubuntu-24.04
            arch: x86
            env_target_file: "fermitools-develop-linux.yml"
          - os: macos-13
            arch: x86_64 
            env_target_file: "fermitools-develop-osx-x86.yml"
            packages: llvm cfitsio swig
          - os: macos-15 # arm64
            arch: arm64
            env_target_file: "fermitools-develop-osx-arm64.yml"
            packages: llvm cfitsio swig
    steps:
      - name: checkout the code
        uses: actions/checkout@v4 # Checkout the repository code
        with:
          ref: master
          submodules: 'recursive' # true
          fetch-depth: 0 # Fetches full history
          
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11
          environment-file: environments/${{matrix.env_target_file}}    # Replace with the path to your conda environment
          conda-remove-defaults: true
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Set environment-specific variables
        run: |
          if [[ "${{ matrix.os }}" == "macos-"* && "${{ matrix.arch }}" == "x86_64" ]]; then
            echo "Setting MacOS x86 env var" # debug
            echo "MACOS_ARCH=x86" >> "$GITHUB_ENV"
          fi

      - name: Increment version number
        run: |
          source ${{ github.workspace }}/recipe/increment_fermi_version.sh
          echo "FERMITOOLS_VERSION=$FERMITOOLS_VERSION" >> "$GITHUB_ENV"

      - name: Create test results directory 
        run: |
          mkdir -p tests
          mkdir -p test_results
          mkdir -p downloaded-test-results
          mkdir -p /tmp/artifacts

      - name: Build and upload the conda packages
        id: conda-build-and-upload
        uses: uibcdf/action-build-and-upload-conda-packages@main
        with:
          meta_yaml_dir: recipe # Replace with the path to your meta.yaml directory
          user: fermi # Replace with your Anaconda username (or an Anaconda organization username)
          token: ${{ secrets.ANACONDA_TOKEN }} # Replace with the name of your Anaconda Token secret
          label: dev
          upload: true

      - name: Re-format output paths
        id: reformat-paths
        # Needed to have the correct newline-separated files format for the following release step
        run: |
            paths=$(tr ' ' '\n' <<< "${{steps.conda-build-and-upload.outputs.paths}}")
            echo "newline-separated-paths=$paths" >> "$GITHUB_OUTPUT"

      - name: Display conda paths
        run: |
            pwd
            ls -l ${{steps.reformat-paths.outputs.newline-separated-paths}}

      - name: Run unit tests
        run: |
           echo "Running unit tests in the testing environment..."
           pwd
           cd  test-results
           conda create --name jsa-testing python=3.11
           conda activate jsa-testing
           conda install astropy junit-xml fermi::fermitools-data fermi::fermitools-test-scripts ${{steps.reformat-paths.outputs.newline-separated-paths}}
           python3 ${{ github.workspace }}//recipe/tests/ST-unit-test
           ls -l

      - name: Publish Test Results Linux
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: runner.os == 'Linux'
        with:
          files: |
             test-results/ST-unit-test-Output.xml
             test_results/ST-*.log
             tests/ST-unit*.xml
             tests/ST-report.xml
             artifacts/test-results/*.xml

      - name: Publish Test Results OSX
        uses: EnricoMi/publish-unit-test-result-action/macos@v2
        if: runner.os == 'macOS'
        with:
          files: |
             test-results/ST-unit*.xml
             test_results/ST-*.log
             tests/ST-unit*.xml
             downloaded-test-results/**/*.xml
             artifacts/test-results/*.xml
