name: Build and upload conda packages

on:
  push:
    branches: master
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
jobs:
  conda_deployment:
    name: Conda deployment
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    defaults:
     run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04-arm
            arch: arm64
            env_target_file: "fermitools-develop-linux.yml"
          - os: ubuntu-22.04
            arch: x86
            container: redhat/ubi8:latest
            env_target_file: "fermitools-develop-linux.yml"
          - os: macos-13
            arch: x86_64 
            env_target_file: "fermitools-develop-osx-x86.yml"
            packages: llvm cfitsio swig
          - os: macos-15 # arm64
            arch: arm64
            env_target_file: "fermitools-develop-osx-arm64.yml"
            packages: llvm cfitsio swig
    steps:
    
      - name: Run environment-specific commands
        run: |
          if [[ "${{ matrix.os }}" == "macos-"* && "${{ matrix.arch }}" == "x86" ]]; then
            echo "Setting MacOS x86 env var" # debug
            echo "MACOS_ARCH=x86" >> "$GITHUB_ENV"
          fi
          if [[ "${{ matrix.os }}" == "ubuntu-"* && "${{ matrix.arch }}" == "x86" ]]; then
            yum -y install git jq
            git config --global --add safe.directory /__w/ScienceTools/ScienceTools
          fi
          
      - name: checkout the code
        uses: actions/checkout@v4 # Checkout the repository code
        with:
          ref: master
          submodules: 'recursive' # true
          fetch-depth: 0 # Fetches full history
          
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environments/${{matrix.env_target_file}}    # Replace with the path to your conda environment
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Increment version number
        run: |
          source recipe/increment_fermi_version.sh
          echo "FERMITOOLS_VERSION=$FERMITOOLS_VERSION" >> "$GITHUB_ENV"
        
      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@main
        with:
          meta_yaml_dir: recipe # Replace with the path to your meta.yaml directory
          user: fermi # Replace with your Anaconda username (or an Anaconda organization username)
          token: ${{ secrets.ANACONDA_TOKEN }} # Replace with the name of your Anaconda Token secret
          label: dev
          upload: true
          

