name: Build and upload conda packages

on:
  push:
    branches: master_testing
jobs:
  conda_deployment:
    name: Conda deployment
    runs-on: ${{ matrix.os }}
    defaults:
     run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04-arm
            arch: arm64
            env_target_file: "fermitools-develop-linux.yml"
          - os: ubuntu-24.04
            arch: x86
            env_target_file: "fermitools-develop-linux.yml"
          - os: macos-13
            arch: x86_64 
            env_target_file: "fermitools-develop-osx-x86.yml"
            packages: llvm cfitsio swig
          - os: macos-15 # arm64
            arch: arm64
            env_target_file: "fermitools-develop-osx-arm64.yml"
            packages: llvm cfitsio swig
    steps:
      - name: Get job context
        id: context-extractor
        uses: qoomon/actions--context@v4.0.3

      - name: checkout the code
        uses: actions/checkout@v4 # Checkout the repository code
        with:
          ref: master_testing
          submodules: 'recursive' # true
          fetch-depth: 0 # Fetches full history
          
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3.2.0
        with:
          python-version: 3.11
          conda-remove-defaults: true
          environment-file: environments/${{matrix.env_target_file}}    # Replace with the path to your conda environment
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Set environment-specific variables
        run: |
          if [[ runner.os != 'macOS' && "${{ matrix.arch }}" == "x86_64" ]]; then
            echo "Setting MacOS x86 env var" # debug
            echo "MACOS_ARCH=x86" >> "$GITHUB_ENV"
          fi

      - name: Increment version number
        run: |
          source ${{ github.workspace }}/recipe/increment_fermi_version.sh
          echo "FERMITOOLS_VERSION=$FERMITOOLS_VERSION" >> "$GITHUB_ENV"
        
      - name: Build and upload the conda packages
        continue-on-error: true
        uses: uibcdf/action-build-and-upload-conda-packages@main
        with:
          meta_yaml_dir: recipe # Replace with the path to your meta.yaml directory
          user: fermi # Replace with your Anaconda username (or an Anaconda organization username)
          token: ${{ secrets.ANACONDA_TOKEN }} # Replace with the name of your Anaconda Token secret
          label: dev
          upload: false
          
      - name: Get Conda package name
        id: get_package_name
        run: |
          PACKAGE_NAME=$(yq '.package.name' conda-recipe/meta.yaml)
          echo "PACKAGE_NAME_CONDA=$PACKAGE_NAME" >> "$GITHUB_ENV"   

      - name: Upload Conda package
        run: |
          echo "Uploaded package: ${{ env.PACKAGE_NAME_CONDA }}"
     
      - name: Publish Test Results for Linux
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: runner.os == 'Linux'
        with:
          files: test-results/ST-unit-test-Output.xml
    
      - name: Publish Test Results for Mac
        uses: EnricoMi/publish-unit-test-result-action/macos@v2
        if: runner.os == 'macOS'
        with: 
          files: test-results/ST-unit*.xml

# Stop updating SLack with every run 08/26/25 JSA        
#      - name: Post a Build status in a Slack's fermitools-pipeline channel.
#        if: always()
#        uses: slackapi/slack-github-action@v2.1.1
#        with:
#          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
#          webhook-type: incoming-webhook
#          payload: |
#            text: "This line is ignored, find a title option..."
#            blocks:
#             - type: "header"
#               text:
#                 type: "plain_text"
#                 text: "Workflow ${{ env.GITHUB_WORKFLOW }} from ${{ github.repository }} branch ${{ github.ref_name }} run ${{github.run_number}} completed."
#             - type: "section"
#               text:
#                 type: "mrkdwn"
#                 text: "*Status*: ${{ job.status }}\n*OS*: ${{ runner.os }}\n*Architecture*: ${{ matrix.arch }}\n*Parent Build URL*: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n*Runner Build URL*: ${{ env.GITHUB_JOB_URL }}"
