name: Build the Conda package
on:
  workflow_call:
    inputs:
      matrix_json:
        required: true
        type: string
        description: "JSON string representing the matrix"
      fermitools_pkg:
        required: true
        type: string
        description: "Location of the Fermitools package"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJson(inputs.matrix_json) }}
    steps:
      - name: Checkout just ScienceTools repo 
        uses: actions/checkout@v4
        with:
          ref: checkout_fixes # master

      - name: Display fermitools_pkg input variable
        run: |
          echo "The input pkg value is: ${{ inputs.fermitools_pkg }}"
          ls -l
          echo "WS ${{ github.workspace }}"
          echo "CPF $CONDA_PREFIX"
          ls -l "$CONDA_PREFIX"
          ls -l ${{ github.workspace }}/environments/fermitools-testing.yml

      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3
        with:
          conda-remove-defaults: true
          python-version: 3.11
          activate-environment: testing-env 
          environment-file: ${{ github.workspace }}/environments/fermitools-testing.yml   # Replace with the path to your conda environment
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Run tests by hand
        id: run_tests_again
        continue-on-error: true # Important: Allow the workflow to continue even if tests fail
        run: |
           echo "Run tests jsa"
           echo "LIB_DIR=$CONDA_PREFIX/lib" >> "$GITHUB_ENV"
           echo "LD_LIBRARY_PATH=$CONDA_PREFIX/lib" >> "$GITHUB_ENV"
           echo " Prove ${{ inputs.fermitools_pkg }}"
           conda install  "${{inputs.fermitools_pkg}}"
           source "$CONDA_PREFIX/etc/conda/activate.d/activate.sh"
           mkdir -p test_results
           cd test_results/
           python ../recipe/tests/ST-unit-test -w -d -v
           ls -l
